Use different WebClient.Builder instances per Retrofit context support non-loadbalancer.
spring-projects-experimental/spring-cloud-square pull request #43
Opened 2022-01-03 06:11 UTC by huahouye

2022-01-12 17:07 UTC, OlgaMaciaszek requested changes
@huahouye Thanks for submitting the PR. Looks good in general. I have added a comment to fix a typo - please address it. Also, please add your full name with `@author` tag to the javadocs of all the classes that you've modified.

2022-01-12 17:07 UTC, OlgaMaciaszek commented on spring-cloud-square-retrofit-webclient/src/test/java/org/springframework/cloud/square/retrofit/webclient/WebClientRetrofitLoadBalancerTests.java
> +	void testCustomWebClientBuilderPickeByRetrofitNameWithoutLoadBalanced() {
Please rename to `testCustomWebClientBuilderPickedByRetrofitNameWithoutLoadBalanced` (typo)

2022-01-12 17:08 UTC, OlgaMaciaszek commented
Fixes gh-44.

2022-01-14 01:34 UTC, huahouye commented
@OlgaMaciaszek done.

2022-01-26 15:23 UTC, OlgaMaciaszek requested changes
Hello, @huahouye - thanks, this is practically done, however, we require full name and surname in the author tags. Please change that and the PR will be good to merge.

2022-01-26 15:23 UTC, OlgaMaciaszek commented on spring-cloud-square-retrofit-webclient/src/main/java/org/springframework/cloud/square/retrofit/webclient/WebClientRetrofitClientFactoryBean.java
> + * @author huahouye
Please use full name and surname here.

2022-01-26 15:23 UTC, OlgaMaciaszek commented on spring-cloud-square-retrofit-webclient/src/test/java/org/springframework/cloud/square/retrofit/webclient/WebClientRetrofitLoadBalancerTests.java
> + * @author huahouye
Please use full name and surname here.

2022-01-26 16:17 UTC, pivotal-cla commented
@huahouye Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects-experimental/spring-cloud-square&pullRequestId=43) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-01-27 04:06 UTC, pivotal-cla commented
@huahouye Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-cloud-square&pullRequestId=43)!

2022-01-27 04:19 UTC, huahouye commented
@OlgaMaciaszek

2022-01-27 11:40 UTC, OlgaMaciaszek approved these changes
Thanks, @huahouye . LGTM.

2022-01-27 11:41 UTC, merged